### ISSUE TITLE
Changing pitch or count values from default causes FreeCAD to crash

### ISSUE THREAD

**Issue by david-coneff** [pyro9/PathHelixTool#1]
I'm running Windows 10, which I should note the developer doesn't have a test environment for.

I managed to get the button installed in the Part WorkBench tool menu and create a helix using a single line segment as the "spine"

When trying to change either the "count" or "pitch" values to something other than the default, this causes a hard crash of FreeCAD (no error messages, the program just exits)

I can change any other attribute in the "dimensions" dialog - e.g., Radius, Reverse, Spine, Rotation and it will recompute the helix correctly.

Given that "count" and "pitch" are parametrically related, it may be something to do with recalculation of the other value, I'm not certain.

Otherwise a really neat contribution to FreeCAD that's clearly needed, hope I can find a way to make it more modifiable.

**Comment by pyro9** [comment]
Give the latest commit a try. I think the problem was an infinite recursion. Pitch changes, onChange called, changes count, onChange called...
In linux that was being caught and terminated. Perhaps not in Windows.

**Comment by david-coneff** [comment]
> Give the latest commit a try. I think the problem was an infinite recursion. Pitch changes, onChange called, changes count, onChange called... In linux that was being caught and terminated. Perhaps not in Windows.

The commit you just posted fixed that. Thank you! Really quick response all things considered.
